name: Wails build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - run: go version

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Linux Wails deps
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu

      - name: Install macOS Wails deps
        if: runner.os == 'macOS'
        run: brew install mitchellh/gon/gon create-dmg

      - name: Build macOS App
        if: runner.os == 'macOS'
        run: |
          wails build --platform darwin/universal
          create-dmg "./build/bin/UnPwd Desktop-mac.dmg" "./build/bin/UnPwd Desktop.app"
          rm -rf "./build/bin/UnPwd Desktop.app"

      - name: Build Linux App
        if: runner.os == 'Linux'
        run: wails build --platform linux/amd64

      - name: Build Windows App
        if: runner.os == 'Windows'
        run: wails build --platform windows/amd64,windows/arm64

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release_on_${{ matrix.os }}
          path: build/bin
          retention-days: 5
